# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title
paginate: 8
paginate_path: "/page:num/"

exclude:
  [
    ".rvmrc",
    ".rbenv-version",
    "README.md",
    "Rakefile",
    "changelog.md",
    "TODO.txt",
  ]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
logo: 🎏
title: Classic Spirits
category: blogging
tagline: A Jekyll Theme for Old-school Blogging!
description: A Jekyll theme for old-school blogging, based off of "Soot Spirits" by Abhishek Nagekar.
about: Hey there! My name is Brennan, I'm a 25-year-old Métis web developer and content strategist from Winnipeg, Manitoba and currently reside in Calgary, Alberta.
avatar: https://brennanbrown.ca/img/avatar.jpg
author:
  name: Brennan K. Brown
  email: mail@brennanbrown.ca
  github: brennanbrown
  twitter: brennankbrown

excerpt_separator: <!--more-->

blogroll:
  - name: xkcd
    url: https://xkcd.com/
  - name: Commit Strip
    url: http://commitstrip.com/
  - name: SMBC Comics
    url: http://www.smbc-comics.com/
  - name: Coding Horror
    url: https://blog.codinghorror.com/
  - name: Wait But Why
    url: http://waitbutwhy.com/
  - name: Simply Soch
    url: https://simplysoch.wordpress.com/

production_url: https://classic-spirits.netlify.app
url: https://classic-spirits.netlify.app
plugins:
  - jekyll-sitemap
  - jekyll-twitter-plugin

# Jekyll-Bootstrap specific configurations:
JB:
  version: 0.3.1
  BASE_PATH: false
  ASSET_PATH: false
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /feed.xml
